name: it_blog
description: "iT Blog"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0
  url_strategy: ^0.2.0
  flutter_svg: ^2.0.10+1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  swipeable_page_route: ^0.4.2
  easy_localization: ^3.0.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.7
  flutter_scale_tap: ^1.0.5
  lottie: ^3.1.0
  dotlottie_loader: ^0.0.3
  injectable: ^2.3.2
  intl: ^0.18.1
  loop_page_view: ^1.2.5
  blur: ^3.1.0
  uuid: ^4.3.3
  sticky_headers: ^0.3.0+2
  dotted_line: ^3.2.2
  timer_builder: ^2.0.0
  animated_text_kit: ^4.2.2
  visibility_detector: ^0.4.0+2
  google_sign_in: ^6.2.1
  form_validator: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.27.1
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/app_icon.png
  min_sdk_android: 21

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png
  android: true
  ios: true

#  dart run flutter_native_splash:create
#  flutter pub run flutter_launcher_icons
#  dart run build_runner watch --delete-conflicting-outputs

